#!/bin/bash

export PATH=$HOME/opt/bin:$PATH

# we error out on the first failure.
set -e
cd source


function new_srcdir_build () {
    echo "building: $1"
    cd $1
    rm -rf build
    mkdir build
    cd build
}


function success () {
    cd ../..
    echo "successfully built: $1"
}


function build_penguin_tower () {
    new_srcdir_build penguin-tower
    ../configure
    make
    success penguin-tower
}


function build_chess_shell () {
    new_srcdir_build chess-shell
    ../configure
    make
    success chess-shell
}


function build_pge () {
    new_srcdir_build pge
    ../configure --enable-langm2
    make
    success pge
}


function build_m2bsk () {
    new_srcdir_build m2bsk
    for i in  ../src/lib/imp/*.mod ; do
	echo gm2 -c -g -I../src/lib  $i
	gm2 -c -g -I../src/lib  $i
    done
    success m2bsk
}


build_pge
build_chess_shell
build_penguin_tower
build_m2bsk
